//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LivraisonRepasService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commandes
    {
        public int Id { get; set; }
        public int Id_Client { get; set; }
        public int Id_Livreur { get; set; }
        public string Contenu { get; set; }
        public string Etat { get; set; }
    
        public virtual Utilisateurs Utilisateurs { get; set; }
        public virtual Utilisateurs Utilisateurs1 { get; set; }
    }
}
