//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 12.0.21005.1
// 
namespace LivraisonRepas.LivraisonRepasUtilisateursServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UtilisateursComposite", Namespace="http://schemas.datacontract.org/2004/07/LivraisonRepasService.Composite")]
    public partial class UtilisateursComposite : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AdresseValueField;
        
        private int IdUtilisateursValueField;
        
        private string PasswordValueField;
        
        private string PseudoValueField;
        
        private string TypeValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdresseValue {
            get {
                return this.AdresseValueField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresseValueField, value) != true)) {
                    this.AdresseValueField = value;
                    this.RaisePropertyChanged("AdresseValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUtilisateursValue {
            get {
                return this.IdUtilisateursValueField;
            }
            set {
                if ((this.IdUtilisateursValueField.Equals(value) != true)) {
                    this.IdUtilisateursValueField = value;
                    this.RaisePropertyChanged("IdUtilisateursValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordValue {
            get {
                return this.PasswordValueField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordValueField, value) != true)) {
                    this.PasswordValueField = value;
                    this.RaisePropertyChanged("PasswordValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PseudoValue {
            get {
                return this.PseudoValueField;
            }
            set {
                if ((object.ReferenceEquals(this.PseudoValueField, value) != true)) {
                    this.PseudoValueField = value;
                    this.RaisePropertyChanged("PseudoValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeValue {
            get {
                return this.TypeValueField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeValueField, value) != true)) {
                    this.TypeValueField = value;
                    this.RaisePropertyChanged("TypeValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Utilisateurs", Namespace="http://schemas.datacontract.org/2004/07/LivraisonRepasService")]
    public partial class Utilisateurs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AdresseField;
        
        private System.Collections.ObjectModel.ObservableCollection<LivraisonRepas.LivraisonRepasUtilisateursServiceReference.Commandes> CommandesField;
        
        private System.Collections.ObjectModel.ObservableCollection<LivraisonRepas.LivraisonRepasUtilisateursServiceReference.Commandes> Commandes1Field;
        
        private int IdField;
        
        private string PasswordField;
        
        private string PseudoField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresse {
            get {
                return this.AdresseField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresseField, value) != true)) {
                    this.AdresseField = value;
                    this.RaisePropertyChanged("Adresse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<LivraisonRepas.LivraisonRepasUtilisateursServiceReference.Commandes> Commandes {
            get {
                return this.CommandesField;
            }
            set {
                if ((object.ReferenceEquals(this.CommandesField, value) != true)) {
                    this.CommandesField = value;
                    this.RaisePropertyChanged("Commandes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<LivraisonRepas.LivraisonRepasUtilisateursServiceReference.Commandes> Commandes1 {
            get {
                return this.Commandes1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Commandes1Field, value) != true)) {
                    this.Commandes1Field = value;
                    this.RaisePropertyChanged("Commandes1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pseudo {
            get {
                return this.PseudoField;
            }
            set {
                if ((object.ReferenceEquals(this.PseudoField, value) != true)) {
                    this.PseudoField = value;
                    this.RaisePropertyChanged("Pseudo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Commandes", Namespace="http://schemas.datacontract.org/2004/07/LivraisonRepasService")]
    public partial class Commandes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ContenuField;
        
        private string EtatField;
        
        private int IdField;
        
        private int Id_ClientField;
        
        private int Id_LivreurField;
        
        private LivraisonRepas.LivraisonRepasUtilisateursServiceReference.Utilisateurs UtilisateursField;
        
        private LivraisonRepas.LivraisonRepasUtilisateursServiceReference.Utilisateurs Utilisateurs1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contenu {
            get {
                return this.ContenuField;
            }
            set {
                if ((object.ReferenceEquals(this.ContenuField, value) != true)) {
                    this.ContenuField = value;
                    this.RaisePropertyChanged("Contenu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Etat {
            get {
                return this.EtatField;
            }
            set {
                if ((object.ReferenceEquals(this.EtatField, value) != true)) {
                    this.EtatField = value;
                    this.RaisePropertyChanged("Etat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Client {
            get {
                return this.Id_ClientField;
            }
            set {
                if ((this.Id_ClientField.Equals(value) != true)) {
                    this.Id_ClientField = value;
                    this.RaisePropertyChanged("Id_Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Livreur {
            get {
                return this.Id_LivreurField;
            }
            set {
                if ((this.Id_LivreurField.Equals(value) != true)) {
                    this.Id_LivreurField = value;
                    this.RaisePropertyChanged("Id_Livreur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LivraisonRepas.LivraisonRepasUtilisateursServiceReference.Utilisateurs Utilisateurs {
            get {
                return this.UtilisateursField;
            }
            set {
                if ((object.ReferenceEquals(this.UtilisateursField, value) != true)) {
                    this.UtilisateursField = value;
                    this.RaisePropertyChanged("Utilisateurs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LivraisonRepas.LivraisonRepasUtilisateursServiceReference.Utilisateurs Utilisateurs1 {
            get {
                return this.Utilisateurs1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Utilisateurs1Field, value) != true)) {
                    this.Utilisateurs1Field = value;
                    this.RaisePropertyChanged("Utilisateurs1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LivraisonRepasUtilisateursServiceReference.ILivraisonRepasUtilisateursService")]
    public interface ILivraisonRepasUtilisateursService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILivraisonRepasUtilisateursService/GetUtilisateurs", ReplyAction="http://tempuri.org/ILivraisonRepasUtilisateursService/GetUtilisateursResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<LivraisonRepas.LivraisonRepasUtilisateursServiceReference.UtilisateursComposite>> GetUtilisateursAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILivraisonRepasUtilisateursService/GetUtilisateur", ReplyAction="http://tempuri.org/ILivraisonRepasUtilisateursService/GetUtilisateurResponse")]
        System.Threading.Tasks.Task<LivraisonRepas.LivraisonRepasUtilisateursServiceReference.UtilisateursComposite> GetUtilisateurAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILivraisonRepasUtilisateursService/AddUtilisateurs", ReplyAction="http://tempuri.org/ILivraisonRepasUtilisateursService/AddUtilisateursResponse")]
        System.Threading.Tasks.Task AddUtilisateursAsync(LivraisonRepas.LivraisonRepasUtilisateursServiceReference.Utilisateurs u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILivraisonRepasUtilisateursService/DeleteUtilisateurs", ReplyAction="http://tempuri.org/ILivraisonRepasUtilisateursService/DeleteUtilisateursResponse")]
        System.Threading.Tasks.Task DeleteUtilisateursAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILivraisonRepasUtilisateursService/UpdateUtilisateurs", ReplyAction="http://tempuri.org/ILivraisonRepasUtilisateursService/UpdateUtilisateursResponse")]
        System.Threading.Tasks.Task UpdateUtilisateursAsync(LivraisonRepas.LivraisonRepasUtilisateursServiceReference.Utilisateurs u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILivraisonRepasUtilisateursService/AuthentificationUtilisateur" +
            "", ReplyAction="http://tempuri.org/ILivraisonRepasUtilisateursService/AuthentificationUtilisateur" +
            "Response")]
        System.Threading.Tasks.Task<LivraisonRepas.LivraisonRepasUtilisateursServiceReference.UtilisateursComposite> AuthentificationUtilisateurAsync(string pseudo, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILivraisonRepasUtilisateursService/ExistePseudo", ReplyAction="http://tempuri.org/ILivraisonRepasUtilisateursService/ExistePseudoResponse")]
        System.Threading.Tasks.Task<bool> ExistePseudoAsync(string pseudo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILivraisonRepasUtilisateursServiceChannel : LivraisonRepas.LivraisonRepasUtilisateursServiceReference.ILivraisonRepasUtilisateursService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LivraisonRepasUtilisateursServiceClient : System.ServiceModel.ClientBase<LivraisonRepas.LivraisonRepasUtilisateursServiceReference.ILivraisonRepasUtilisateursService>, LivraisonRepas.LivraisonRepasUtilisateursServiceReference.ILivraisonRepasUtilisateursService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LivraisonRepasUtilisateursServiceClient() : 
                base(LivraisonRepasUtilisateursServiceClient.GetDefaultBinding(), LivraisonRepasUtilisateursServiceClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ILivraisonRepasUtilisateursService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LivraisonRepasUtilisateursServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(LivraisonRepasUtilisateursServiceClient.GetBindingForEndpoint(endpointConfiguration), LivraisonRepasUtilisateursServiceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LivraisonRepasUtilisateursServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LivraisonRepasUtilisateursServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LivraisonRepasUtilisateursServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LivraisonRepasUtilisateursServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LivraisonRepasUtilisateursServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<LivraisonRepas.LivraisonRepasUtilisateursServiceReference.UtilisateursComposite>> GetUtilisateursAsync() {
            return base.Channel.GetUtilisateursAsync();
        }
        
        public System.Threading.Tasks.Task<LivraisonRepas.LivraisonRepasUtilisateursServiceReference.UtilisateursComposite> GetUtilisateurAsync(int id) {
            return base.Channel.GetUtilisateurAsync(id);
        }
        
        public System.Threading.Tasks.Task AddUtilisateursAsync(LivraisonRepas.LivraisonRepasUtilisateursServiceReference.Utilisateurs u) {
            return base.Channel.AddUtilisateursAsync(u);
        }
        
        public System.Threading.Tasks.Task DeleteUtilisateursAsync(int id) {
            return base.Channel.DeleteUtilisateursAsync(id);
        }
        
        public System.Threading.Tasks.Task UpdateUtilisateursAsync(LivraisonRepas.LivraisonRepasUtilisateursServiceReference.Utilisateurs u) {
            return base.Channel.UpdateUtilisateursAsync(u);
        }
        
        public System.Threading.Tasks.Task<LivraisonRepas.LivraisonRepasUtilisateursServiceReference.UtilisateursComposite> AuthentificationUtilisateurAsync(string pseudo, string password) {
            return base.Channel.AuthentificationUtilisateurAsync(pseudo, password);
        }
        
        public System.Threading.Tasks.Task<bool> ExistePseudoAsync(string pseudo) {
            return base.Channel.ExistePseudoAsync(pseudo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ILivraisonRepasUtilisateursService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ILivraisonRepasUtilisateursService)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:45719/LivraisonRepasUtilisateursService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return LivraisonRepasUtilisateursServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ILivraisonRepasUtilisateursService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return LivraisonRepasUtilisateursServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ILivraisonRepasUtilisateursService);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_ILivraisonRepasUtilisateursService,
        }
    }
}
