//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LivraisonRepasServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuRestaurant
    {
        public int id { get; set; }
        public Nullable<int> idRestaurant { get; set; }
        public Nullable<int> idMenu { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
