//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LivraisonRepasServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.MenuRestaurant = new HashSet<MenuRestaurant>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public Nullable<double> prix { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<int> idRestaurant { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual ICollection<MenuRestaurant> MenuRestaurant { get; set; }
    }
}
